export const PERMISSIONS = {
  FLEET_VIEW: 'fleet:view',
  FLEET_MANAGE: 'fleet:manage',
  VEHICLE_VIEW: 'vehicle:view',
  VEHICLE_COMMAND: 'vehicle:command',
  COMMAND_CREATE: 'command:create',
  COMMAND_APPROVE: 'command:approve',
  COMMAND_EXECUTE: 'command:execute',
  AUDIT_VIEW: 'audit:view',
  AUDIT_VERIFY: 'audit:verify',
  THREAT_VIEW: 'threat:view',
  THREAT_SIMULATE: 'threat:simulate',
  ANALYTICS_VIEW: 'analytics:view',
  COMPLIANCE_VIEW: 'compliance:view',
  COMPLIANCE_MANAGE: 'compliance:manage',
  ORG_VIEW: 'org:view',
  ORG_MANAGE: 'org:manage',
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_MANAGE: 'settings:manage',
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: Object.values(PERMISSIONS),
  financier: [PERMISSIONS.FLEET_VIEW, PERMISSIONS.VEHICLE_VIEW, PERMISSIONS.VEHICLE_COMMAND, PERMISSIONS.COMMAND_CREATE, PERMISSIONS.COMMAND_APPROVE, PERMISSIONS.AUDIT_VIEW, PERMISSIONS.ANALYTICS_VIEW, PERMISSIONS.COMPLIANCE_VIEW],
  fleet_operator: [PERMISSIONS.FLEET_VIEW, PERMISSIONS.FLEET_MANAGE, PERMISSIONS.VEHICLE_VIEW, PERMISSIONS.VEHICLE_COMMAND, PERMISSIONS.COMMAND_CREATE, PERMISSIONS.AUDIT_VIEW, PERMISSIONS.ANALYTICS_VIEW],
  driver: [PERMISSIONS.VEHICLE_VIEW, PERMISSIONS.AUDIT_VIEW],
  auditor: [PERMISSIONS.FLEET_VIEW, PERMISSIONS.VEHICLE_VIEW, PERMISSIONS.AUDIT_VIEW, PERMISSIONS.AUDIT_VERIFY, PERMISSIONS.ANALYTICS_VIEW, PERMISSIONS.COMPLIANCE_VIEW],
  regulator: [PERMISSIONS.FLEET_VIEW, PERMISSIONS.VEHICLE_VIEW, PERMISSIONS.AUDIT_VIEW, PERMISSIONS.COMPLIANCE_VIEW, PERMISSIONS.COMPLIANCE_MANAGE],
  oem: [PERMISSIONS.FLEET_VIEW, PERMISSIONS.VEHICLE_VIEW, PERMISSIONS.ANALYTICS_VIEW],
};

export function hasPermission(role: string, permission: string): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
