export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  APP: '/app',
  DASHBOARD: '/app/dashboard',
  FLEET: '/app/fleet',
  VEHICLE_DETAIL: '/app/fleet/:id',
  DIGITAL_TWIN: '/app/digital-twin',
  COMMAND_CENTER: '/app/command-center',
  APPROVALS: '/app/approvals',
  THREAT_SANDBOX: '/app/threat-sandbox',
  VERIFICATION: '/app/verification',
  AUDIT: '/app/audit',
  ANALYTICS: '/app/analytics',
  COMPLIANCE: '/app/compliance',
  DRIVER_PORTAL: '/app/driver-portal',
  ORGANIZATION: '/app/organization',
  SETTINGS: '/app/settings',
  NOTIFICATIONS: '/app/notifications',
  HELP: '/app/help',
  RELEASE_NOTES: '/app/release-notes',
  SCENARIO_SIMULATOR: '/app/scenario-simulator',
  JUDGE_DEMO: '/judge-demo',
} as const;
